version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  web:
    build:
      context: ./rails
      dockerfile: ./docker/rails/Dockerfile
    env_file: .env
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/rails
      - bundle-data:/usr/local/bundle
      - ~/.ssh:/root/.ssh
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  front:
    build:
      context: ./rails
      dockerfile: ./docker/react/Dockerfile
    env_file: .env
    command: sh -c "cd /rails/front && npm start"
    volumes:
      - ./rails/front:/rails/front
      - bundle-data:/usr/local/bundle
      - ~/.ssh:/root/.ssh
    ports:
      - "4000:3000"

volumes:
  mysql-data:
  bundle-data:
