version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  back:
    build:
      context: ./back
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back:/myapp
      - bundle-data:/usr/local/bundle
      - ~/.ssh:/root/.ssh
    ports:
      - "4000:3000"
    depends_on:
      - db

  front:
    build:
      context: ./front
    command: yarn start
    volumes:
      - ./front:/myapp
      - ~/.ssh:/root/.ssh
    ports:
      - "5000:3000"
    depends_on:
      - back

volumes:
  db-data:
  bundle-data:
